name: Build Syntropy Agent GO

on:
  push:
    branches:
      - main
      - v0.1.0
    tags:
      - '*'

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: test
        run: echo running on branch ${GITHUB_REF}
      -
        name: SANDBOX Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:go-sandbox
          platforms: linux/amd64
      -
        name: DEVEL Build and push
        if: contains(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: syntropynet/agent:go-devel
      -
        name: PROD Build and push
        # BRANCH_STABLE_VERSION
        if: github.ref == 'refs/heads/v0.1.0'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:go-prod
            syntropynet/agent:go-stable
