name: build

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
    tags:
      - '*'

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0 --candidates=1)"
      - name: Set vars for commit id
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        # Stable release is a tag `X.Y.Z` without any metadata
      - name: Check stable release
        uses: actions-ecosystem/action-regex-match@v2
        id: stablerelease
        with:
          text: ${{ github.ref }}
          regex: ^refs\/tags\/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: SANDBOX Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:sandbox
            syntropynet/agent:alpha
          platforms: linux/amd64
          build-args: |
             AGENT_VERSION=${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}
      -
        name: DEVEL Build and push
        if: contains(github.ref, 'beta')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:devel
            syntropynet/agent:beta
            syntropynet/agent:${{ steps.previoustag.outputs.tag }}
      -
        name: PROD Build and push
        if: ${{ steps.stablerelease.outputs.match != '' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:stable
            syntropynet/agent:prod
            syntropynet/agent:${{ steps.previoustag.outputs.tag }}
